### ISSUE TITLE
32GB SDCard locks up on boot

### ISSUE THREAD

**Issue by NonaSuomy** [emukidid/swiss-gc#153]
When Swiss is booted with a 32gb card in the GameCube, 

It scans the Slot B and locks up with the message "Reading  SD in slot B" on the screen.

If I leave the card out, 

Boot and then hit B then hit eject to show the SD Card menu option, 

Then put the SD Card in and select the SD Card option, 

It will scan and read the card fine and loads files.

Running Swiss R382 Release.

**Comment by NonaSuomy** [comment]
Found out if no SD Card is in the SD Converter card it makes SWISS lock up so is it locking up because sometimes it can't read the sd card in the converter, ideally, should swiss lockup if nothing is in the sd card converter?

I took it apart and there are zero passive components on the board basically just a straight through pass memory card to sd card with traces between them.

**Comment by emukidid** [comment]
Swiss/no software can detect if something is in the SD Gecko device because it's always shorting the sense lines making any software just know "hey, something is in the memory card slot". So the only way to do it is to try and initialise the card. If there's no card or it fails to read, it's setup to try again because some crappy cards take a while, that's why it hangs.

**Comment by NonaSuomy** [comment]
So is there not a way to say if tried to read x times just proceed to dashboard instead of hanging?
