### ISSUE TITLE
Paper Mario Thousand Year Door freezing

### ISSUE THREAD

**Issue by SmokeyJBluntz** [emukidid/swiss-gc#155]
Game freezing while leveling up to level 10. Can be reproduced anywhere in the game after any battle. Changing video settings to "no" will let it get a little further, but still freezes before leveling up scene is complete

**Comment by emukidid** [comment]
Can you please provide the following:
1. Save File (.gci format, use something like GCMM to put it onto the SD card) and instructions from the save file explaining how to level up (it has been a while since I've played it)
2. What device is this issue present on? (e.g. SD in memory card slot, DVD-R, etc)

**Comment by emukidid** [comment]
Duplicate of issue 205.
