### ISSUE TITLE
Megaman Anniversary Collection Instant Fatal Error On Startup

### ISSUE THREAD

**Issue by AlexS2412** [emukidid/swiss-gc#182]
When Played from the SD Gecko, It always says "FATAL: Set your working directory correctly you MUPPET!!!!" and never starts :p

**Comment by grogfella** [comment]
This is happening to me too: Either the game loads onto a completely blank screen (even when booting off the disc), decides not to launch because of too many patches, or loads into the "FATAL: Set your working directory correctly you MUPPET!!!!" screen.

I've been trying all kinds of variations on ISO files, patches and cheats to get the game to run, even downgrading to a different version of Swiss, but no such luck. It's a shame too because Swiss is really my only option for playing Anniversary Collection with the button hack that swaps A and B functions.

**Comment by AlexS2412** [comment]
Have you tried GCOS yet?

**Comment by grogfella** [comment]
GCOS was of no help: I don't have a network adapter I can use to dump discs. Installing a cheat engine to Qoob has also yielded no results.
