### ISSUE TITLE
XIII - console reboots if the iso is loaded from SD card

### ISSUE THREAD

**Issue by iaros** [emukidid/swiss-gc#220]
**Game**
XIII
**Region**
PAL
**Medium**
SD Gecko
**Swiss version**
Swiss r599, r563
**Detailed report of the issue:**
The game boots, i.e. I can get to the main menu with start/options/load selection, however either i hit continue or start a new game, the console reboots.
The backup runs fine directly from DVD-R as well as if it is loaded from a DVD-R from Swiss.
The backup's checksum corresponds to the one from redump.org
**HW setup:**
DOL-001(EUR) + Chinese Xen8GC (version which only has red leds) + WiiSD adapter + SanDisk Ultra SDHC 32 Gb class 10 (48 Mb/s) SD card

Note: It was described as compatible in the Wiki for swiss version 0.3 onwards...

**Comment by iaros** [comment]
As a follow-up - in release 646 still the same issue occurs.
Additionally, when tried with Alternate read patches enabled, the game crashes immediately after the language selection screen with the in-game message displayed "An unknown error has occurred. Please shut down console [...]"

**Comment by Tommy1995gc** [comment]
Hi there, 
I am writing you because I have solved the same problems that occured to me in these months too! 
Using swiss 0.4 in release version 683, you have to change the AVE Compatibility from "GcVideo(default)" to "AVE N-DOL". This change will fix the console reboots and black screen problems and you can enjoy the game ;) 
I guess the problems can also be fixed with the newest version (Swiss v0.4r685), you can find it here: https://github.com/emukidid/swiss-gc/releases

Yours truly, 
Thomas

**Comment by Extrems** [comment]
The AVE Compatibility option is unrelated, but this game is indeed fixed now.

**Comment by Tommy1995gc** [comment]
I know it but when I tried it 4 hours ago, I was so happy and I couldn't believe it myself it really worked! :)

**Comment by iaros** [comment]
Oh my gosh, finally somebody read this!
Thanks a bunch, will test it.

**Comment by Tommy1995gc** [comment]
I know it, I read it a few months ago but I hadn't solved your problem in that period, but later, when I tried various options I have found that the AVE Compatibility option seems to be the correct option to fix problems, in my case of course. 
Don't forget to save the option after you change it, otherwise you have to change it everytime you launch XIII

Yours truly, 
Thomas
