### ISSUE TITLE
Issue with 683 and 685

### ISSUE THREAD

**Issue by ForeverGCInsomnia** [emukidid/swiss-gc#250]
The latest version is giving me a weird issue. Whenever I burn it onto a disc, whatever speed / settings / burning program, it only get's detected every few tries. I get alot of read errors and have to shutdown and restart the gamecube until it detects the 685 version. I haven't had this issue with any other version of swiss. Also, with version 683 and 685, whenever I load up Pokemon XD: Gale of Darkness I get a black screen and that's it, it doesn't play the game and stays black. With 634 I can play the game without a hassle and it's very smooth. I think the alternate read patches made it very smooth (I enabled it in 634) , no more stuttering issues. However, the latest version is giving me other issues. Does anyone know what the possible cause may be?

**Comment by emukidid** [comment]
I was a little confused until you mentioned that it's the dvd-r with Swiss itself that takes a few tries to boot. Something in your setup, discs, burner, or GameCube laser has changed since your last burn if you're saying the other one was (and still is) working fine.

If you have a SD based device plugged into either slot A, B or SP2, why not just have the 650 boot disc just load boot.dol from the root of your SD card on boot? This way you can put a newer version of Swiss on the SD card and not have to endlessly burn discs for every update.

Can you make a separate issue for the Pokemon XD issue as I'd like to close this one out to setup/hardware related.

**Comment by AndehX** [comment]
> If you have a SD based device plugged into either slot A, B or SP2, why not just have the 650 boot disc just load boot.dol from the root of your SD card on boot? This way you can put a newer version of Swiss on the SD card and not have to endlessly burn discs for every update.

This is extremely interesting.  Can you elaborate on how to do this, or point me to a guide or something that explains how to do this?

**Comment by ForeverGCInsomnia** [comment]
> I was a little confused until you mentioned that it's the dvd-r with Swiss itself that takes a few tries to boot. Something in your setup, discs, burner, or GameCube laser has changed since your last burn if you're saying the other one was (and still is) working fine.
> 
> If you have a SD based device plugged into either slot A, B or SP2, why not just have the 650 boot disc just load boot.dol from the root of your SD card on boot? This way you can put a newer version of Swiss on the SD card and not have to endlessly burn discs for every update.
> 
> Can you make a separate issue for the Pokemon XD issue as I'd like to close this one out to setup/hardware related.

That's correct. I burned it onto a disc and it took a few tries for the gamecube to recognize it (no matter how often I burned it). Sometimes it gets recognized, sometimes it does not. There hasn't changed anything regarding burning setup (using same discs/burner/pc as before). I will indeed boot the newest version off the device instead of burning it onto a disc for now. I will make a seperate issue for Pokemon XD.
