### ISSUE TITLE
Pokemon XD not running on latest versions.

### ISSUE THREAD

**Issue by ForeverGCInsomnia** [emukidid/swiss-gc#254]
Pokemon XD Gale of Darkness isn't booting on the newest versions (650, 683 and 685). It shows a black screen when I boot it and it stays like that. 

It does boot on 634 however, and it does so with alternate reading patches enabled. It also runs very smooth compared to older editions, so I don't know if there is a direct relation. I don't experience the "stutter" that I experience in other versions.

**Comment by Tommy1995gc** [comment]
Hi there, 

Try to change the AVE Compatibility from "GcVideo(default)" to "AVE N-DOL". 
If it doesn't work, try the other AVE Compatibility options
I hope I was helpful. 

Yours truly, 
Thomas

**Comment by ForeverGCInsomnia** [comment]
I don't know why Tommy1995gc his comment got deleted, perhaps a mistake. I do have to say that was the solution to my problem. It worked when I changed it from GCVIDEO to the CMPV-DOL. Weird, since I am using a GCVIDEO, but the game is working now, no more black screen. Is there any downside on running CMPV instead of GCVideo?

This was his comment (so people can read the original suggestion):

Hi there,

Try to change the AVE Compatibility from "GcVideo(default)" to "AVE N-DOL".
If it doesn't work, try the other AVE Compatibility options
I hope I was helpful.

Yours truly,
Thomas

**Comment by Tommy1995gc** [comment]
I don't know what have you done with my comment, why have you deleted it???

About downsides, I tried "XIII the videogame" and the only downsides I have
noticed are that the image is a little dirty (there are some moving lines
over the testa, such as 60hz video mode) and there is a vertical line on
the right of the screen...

I am glad that I have solved your problem with Pokemon XD Gale of Darkness.
I don't know why but nobody thanks me when I fix some problems :(

Yours truly,
Thomas



Il dom 3 nov 2019, 22:43 ForeverGCInsomnia <notifications@github.com> ha
scritto:

**Comment by Tommy1995gc** [comment]
I am so sorry but there is a stupid guy (@Extrems,of course) that is
deleting my own comment because in his opinion I am doing misinformation
since I don't know what I am doing and I am misusing the AVE Compatibility
video option!
What??? It is a regular video option, nothing more! Just like NTSC or 60hz

In his opinion I am not helping users with that fix.
You have been lucky that you have read the comment just in time but people
who is having the same problem now can't do it anymore and it is a real
shame!
Maybe he told me that because I don't have any experience in programming
but I guess it is useless in that case, since I am not damaging or modding
my Nintendo Gamecube...
Thank you for informing me about that but I guess I won't help users
anymore and I will close my github.com account...

Yours truly,
Thomas

Il lun 4 nov 2019, 00:12 Thomas Scorrano <thomasscorrano@gmail.com> ha
scritto:

**Comment by Tommy1995gc** [comment]
This is what I have just written to him:

"Are you joking, right?

I know what I am doing!
It is a normal video setting, nothing more! By activating it, you can play
games in a different video mode, just like NTSC or 60hz, and Nintendo
Gamecube/Wii supports it perfectly since many videogames have the option to
switch from 50hz to 60hz.
I am not activating a 1080i resolution or what, I know that there is that
option too, (CMPV-DOL) but as you can see from the attached pic, AVE N-DOL
description says: "Output PAL as NTSC 50"
Is it misinformation or misuse???

Usually swiss launches games in a 576p video mode when Nintendo
Gamecube/Wii has a 480p standard resolution

In your opinion, I don't have to play XIII because I don't know what I am
doing?

If you don't remember, you were the one who added the AVE Compatibility, if
you don't trust me, I attach you some pics!

I don't think I am doing misinformation if I use a video option that the
one who added it was really you!


I know I am not expert in programming but I also know that I am using a
safe option that fixes various videogames without damaging the console

Think twice before saying something and deleting users comments without a
particular reason!

Yours truly,
Thomas"

I don't know how people can be so stupid and bad! I am helping users and he
says me that I am doing misinformation!
It is a regular global setting, moreover he was the one Who added it!
I don't think that he added that option without a reason but I think it is
used to fix problems!



Il dom 3 nov 2019, 22:42 ForeverGCInsomnia <notifications@github.com> ha
scritto:

**Comment by Tommy1995gc** [comment]
Hi there,

Try to change the AVE Compatibility from "GcVideo(default)" to "AVE N-DOL".
If it doesn't work, try the other AVE Compatibility options (the best option is "CMPV-DOL") 
I hope I was helpful.

Yours truly,
Thomas

**Comment by Tommy1995gc** [comment]
I have read your mail and I am glad I am helpful, please read my previous
in order to understand what happened, leave a feedback and close the issue.

Yours truly,
Thomas

Il lun 4 nov 2019, 10:00 Thomas Scorrano <thomasscorrano@gmail.com> ha
scritto:

**Comment by Tommy1995gc** [comment]
Have you solved your problem? 
If not, like @Extrems said to me before, try to clean out swiss_patches folder or enable/disable Alternate Read Patches. 

Yours truly, 
Thomas

**Comment by Extrems** [comment]
Fixed in cc56956.
