### ISSUE TITLE
Ikaruga keeps looping on start menu

### ISSUE THREAD

**Issue by gkralicek26** [emukidid/swiss-gc#256]
When running Ikaruga using the alternate read patches, the games loads ok and bring you to the main menu but when trying to start a game, the next screen takes you back to the main menu endlessly. I understand the current swiss release doesn't support audio streaming when using alternate read patches but the game should at least run without the background music.

**Comment by emukidid** [comment]
For this to be resolved using the alternate read patch it will basically need to have completely implemented audio streaming anyway since this game and a few others actually check the status of the audio being streamed to see what position it's currently playing from.

I'll close this for now but it will be resolved when those patches support audio streaming. In the meantime please use the non alternate read patches for Ikaruga.
