### ISSUE TITLE
Strange behaviour using WASP on swiss r685

### ISSUE THREAD

**Issue by kiwanowski** [emukidid/swiss-gc#258]
I noticed a strange behaviour of my WASP on swiss r685. Im not sure since what version does it behave like this as I didnt update in quite some time.
When I boot for example the Fire Emblem game, the next time I boot my console, it autoboots directly into Fire Emblem omitting swiss.
With other games like for example Metroid Prime 2 it shows that an MP2 disc is insterted but it boots to a black screen. Other games just show a disc error.
Ive seen some people reporting black screens on WASP with the latest swiss Im wondering if its the same thing.

**Comment by emukidid** [comment]
When Swiss boots an ISO on the WASP it sets the base read offset to this file. This is basically like loading a disc, every read performed from the "dvd drive" will be pointed at this ISO. If you reboot fast enough or your WASP somehow has power continuously throughout a hard reboot then it will still report the last played ISO in the original menu. It'll fail to boot because it's either fragmented or it's not having a region patch applied to it and so on.

This behaviour hasn't changed recently so I'm not sure why you're only noticing it now.

**Comment by kiwanowski** [comment]
I also started using gcvideo in my setup so maybe its not related to the swiss update. Let me just add that sometimes it can remember the last disc used for one hour after power off

**Comment by emukidid** [comment]
This is specific to something in your set up, if you hard power down (pull the power out) and it fixes this, then I'd have your installation double checked to see that your WKF isn't always powered on via some incorrect wiring.
