### ISSUE TITLE
 v0.4r747 and  v0.4r748 Metal Gear Solid Twin Snake not booting with GC loader.

### ISSUE THREAD

**Issue by mike2love** [emukidid/swiss-gc#280]
Works perfectly on  v0.4r743, but after that version you get error shared mysql rel...  see picture for reference.
![20191228_171005](https://user-images.githubusercontent.com/17815582/71551254-c3343300-2997-11ea-8618-f43af55e5ca7.jpg). Most 2 disc games will not boot, including Baten Kaitos: Eternal Wings and the Lost Ocean.

**Comment by danielkraak** [comment]
This is a problem with GC Loader. GC Loader accidentally tries to read from the second disc. This will be fixed in a firmware update very soon. 

Right now, there is not much point in playing 2 Disc games with GC Loader, Since GC Loader cannot yet switch disc during gameplay. Unless there are games that also work if you just boot the second disc once it becomes required??

**Comment by mike2love** [comment]
Awesome, thx for the info. I will wait for the firmware update and close the issue.

**Comment by Extrems** [comment]
Fixed in e908e78 (r751).

**Comment by Extrems** [comment]
Fixed in [firmware 1.0.0](https://github.com/danielkraak/GC-Loader/releases/tag/1.0.0).
