### ISSUE TITLE
Unable to force run Swiss in 60hz

### ISSUE THREAD

**Issue by Darksoftner** [emukidid/swiss-gc#323]
I have a PAL GameCube and I am using the Windwaker exploit to launch Swiss on a NTSC consumer CRT. Once I am in Swiss the image does not sync. I try to guess my way through the menu and at times I am able to launch a GameCube game. The ntsc games runs perfectly. I just can’t make full useful of Swiss since my tv cannot display in 50hz. I hope you can help find a solution for this. Thank you.

**Comment by Darksoftner** [comment]
GameCube Region: PAL
Model: Dol 001
Swiss: v0.4r798
Method: Windwaker (pal) exploit
Cable: RGB Scart sync on CVBS
Connection: Shinybow (Scart to Component converter)
TV: Sony NTSC CRT

**Comment by Papy-G** [comment]
Try to edit your SWISS.ini file from a PC to force SWISS to display in 60Hz.

**Comment by Darksoftner** [comment]
Yeah, it worked out. Thank you so much for your help.

**Comment by Chuckles1001** [comment]
> from a PC to force SWISS to display in 60Hz

Hi Darksoftner, what did you add to change it i can not see anywhere in the "global.ini" file to edit to 60Htz? Thanks :)

**Comment by Papy-G** [comment]
It's just at the beginning of the global.ini:
Swiss Video Mode=480i
The refreshing frequency is implied by the number of lines, so you won't read 60 or 50 Hz in the file.

_I thought the default mode had been reverted back to 60Hz modes on PAL consoles, thus I had to set to 576p for my specific use instead of leaving it to default. (I get back to SWISS via IGR before turning off the console, to be able to use SunshineHack)._
