### ISSUE TITLE
RVZ format support?

### ISSUE THREAD

**Issue by wfowler1** [emukidid/swiss-gc#467]
Somewhat recently, Dolphin came out with the ability to compress ROMs in a format called RVZ. This format is able to completely do away with almost all junk data in a GameCube or Wii disk image, leaving only the actual game data. On disk images such as the GameBoy Player Startup Disk, it brings the filesize from 1.4GB down to only 4.6MB.
It would be awesome if Swiss could load ROMs in this format, it would allow you to store every game in the GameCube library _on a single 1TB SD card_, with plenty of room to spare for things like homebrew and emulators.

**Comment by Papy-G** [comment]
It already supports NKit reduced format, from somewhat, not quite recently, that does almost that, but is not compressed so we won't have to lenghten the loading wait.
The GameBoy Player startup disk takes 5,1MB, and I have an average size of ~1GB per game on my own games collection, which is not bad.

IMHO, homebrews and emulators are better on smaller FAT16 volumes since all homebrews don't support fat32, and I also share those cards with hardware/software that don't support it as well (MK3 DS/Supercard SD/lameboy/SNESDS…).

**Comment by rapperskull** [comment]
NKit is far from perfect. It has flaws that prevent certain games from working. RVZ was developed to specifically address these limitations. Also, [NKit will switch to RVZ](https://gbatemp.net/threads/nkit-recover-to-redump-images-shrink-and-preserve-wii-and-gamecube-disc-images-as-playable.548479/page-8#post-9222656).

**Comment by Extrems** [comment]
RVZ is not happening, unless you want poor game compatibility from the hypervisor eating so much memory.
The plan is to switch to `.nkit.ciso`.
