### ISSUE TITLE
Star Fox: Assault

### ISSUE THREAD

**Issue by GAMECUBE-N64** [emukidid/swiss-gc#504]
I get to this screen and waited 15 to 20 minutes:

Accessing Memory Card... Do not touch the Memory Card in Slot A or the Power Button.
And nothing happened.

I am guessing it is not recognizing virtual memory.

**Comment by Extrems** [comment]
Cannot reproduce.

**Comment by GAMECUBE-N64** [comment]
What do You mean You can't reproduce?

**Comment by emukidid** [comment]
Provide more detail on your current setup and you might have a shot at getting the issue reproduced by someone else for further investigation?

**Comment by GAMECUBE-N64** [comment]
It is set to basic for virtual memory. Start the game and goes to the
memory card screen I told you about. Sat waiting for 15 to 20 minutes and
nothing happened. Like it stuck or something.

**Comment by GAMECUBE-N64** [comment]
The only Swiss settings I use is Configuration Device: SD Card- Slot B. 
Emulate Memory Card: Yes.
I don't mess with any of the other Swiss settings, for me there is no need to.

Then I start The Star Fox: Assault ISO. 

It goes to the Warning Health Screen and the bottom it says, Press any button to continue.
So I do.
Then it goes thru the Nintendo Logo and the Star Fox: Assault video game cut scene movie.
Then it loads and gets to this Screen, Accessing Memory Card... Do not touch the Memory Card in Slot A or the Power Button.
It just hangs there. I waited 15 to 20 minutes  and nothing.

**Comment by GAMECUBE-N64** [comment]
Never mind I know what I did wrong. I have it working now. Sorry.

**Comment by Extrems** [comment]
Maybe you should tell us what you did wrong?

**Comment by GAMECUBE-N64** [comment]
Well. When I play a game and I am done I have to shut the Gamecube off and then turn it back on so I can load a different game. Found out the setting for Virtual Memory On was turning itself off. So Now before I start a new game I go into Swiss settings to make sure it is on. It is a habit now. It is to bad that there isn't a way while playing a game You couldn't do a long press of the Start button or a long press of the Z button to take You back to the Swiss menu without having to shut off the Gamecube and turn it back on just to get to the Swiss Menu to chose another game to play.

**Comment by Extrems** [comment]
But you can. It's the In-Game Reset option.

**Comment by GAMECUBE-N64** [comment]
And so how do You do this???

**Comment by Extrems** [comment]
Press the Y button on the option for help.

**Comment by BurgrDog** [comment]
Request to re-open this Issue. I am experiencing this issue with Star Fox Assault.

Issue: Star Fox Assault is freezing on attempt to access emulated memory card

Swiss version: Latest (to date) - v0.6r1458
GameCube Hardware: DOL-101(USA) (C/L-DOL-USA-VA-2)

File: Star Fox - Assault (USA).nkit.iso
File source: Redump - processed through NKit Processing App (converted to NKit.iso)
Attachments: Zip of Swiss settings ini, Memory Card A USA raw file, IPL dol file (r1458); screenshot of the screen it freezes on (screenshot from Dolphin, for demonstration purposes only)

Reproduction steps:  
I am able to reproduce the issue every time. With the Emulated Memory Card enabled, the game will freeze after:
  1. Skipping or completing the opening video
  2. After the opening video, it goes to a loading screen, then goes to the 'Accessing Memory Card' screen and freezes

Troubleshooting: Turning the Emulate Memory Card setting to 'Off' and this issue does not appear. Using a Nintendo (1st party) Memory Card, or choosing to play with no memory card, and the game proceeds without issue. This is directly related to the Emulated Memory Card in Swiss only. (Only game I've had freeze with Swiss on the Emulated Memory Card, so it seems odd). Attempted plain Redump ISO - non-NKit - and the issue is the same: emulated Memory Card results in a frozen screen.

MD5s:
Star Fox - Assault (USA).nkit.iso - 68c3f812000673eb3363041c0ded0169
Star Fox - Assault (USA).iso - 992e00b7df1960d4ca03c76801502f91

Attachments:
[SwissSetup.zip](https://github.com/emukidid/swiss-gc/files/11416509/SwissSetup.zip)
![StarFoxAssault-Frozen-SwissVirtualMemCard](https://user-images.githubusercontent.com/36521199/236711227-0af94800-cf16-44a7-b0fb-eb47092ccc84.png)

**Comment by Atomic-Germ** [comment]
This is a very real and still-present issue, and easily reproduced by following OP's directions. There's no reason for this to be closed other than the "works for me" which is a huge dev red flag. I'm going to attempt fixing this in my fork.

---

UPDATE: Turns out EMU_MEMCARD requires BS2 init for OSLoMem & EXI, which aren't initiated without the BIOS loading (which I guess used to be called boot through IPL)
