### ISSUE TITLE
BUZZING NOISE

### ISSUE THREAD

**Issue by Casper192** [emukidid/swiss-gc#529]
Getting a buzzing noise on the main menu when using a save game exploit to boot, also monkey balls is freezing up at the menu or a few seconds in to the game.
the buzzing stops when the game starts.

using version v5.1086   game exploit super Mario sunshine (pal)
Monkey balls 1 USA version

**Comment by Extrems** [comment]
It's not our fault if the exploit author didn't stop audio DMA.
I'm unable to reproduce the other problem.

**Comment by vaderag** [comment]
@extrems @casper192
I found a fix

Okay - I've found a working solution to fix this seamlessly!

Instructions...
Get dolaunch from here: https://github.com/suloku/dolaunch/releases/tag/0.2-dolxz
Stick boot.gci of the standard version onto your memory card to get the DOL to be used with Shinehax
Put Swiss on your SD card (if using SD2SP2 as I am) and rename to autoexec.dol)

Load Shinehax as usual - no terrible beep!

**Comment by cobhc2019** [comment]
@vaderag I've tried this solution and tried multiple versions of dolaunch at the link you provided and it seems to just reboot my GC once it tries to load. I have Swiss on my SD2SP2 renamed to autoexec.dol and it's still just rebooting my GC. Can you tell me which exact archive to download? I'm aware this issue is over 2 years old now, but any help would be appreciated if possible.
