### ISSUE TITLE
boot.dol

### ISSUE THREAD

**Issue by HanaO00** [emukidid/swiss-gc#588]
Hello, I found this comment below, I wondered if it would be possible to add a feature, first check if there is a boot.dol on an SD2SP2 and then check on a SD Gecko? It could be practical for people who have both.

I just burn the latest version of Swiss, and I read that there were people who have problems, to automatically start the boot.dol from an SD2SP2, I'm waiting for the next version to try the boot.dol
Thank you

![Screenshot-2021-09-25_21-43-19](https://user-images.githubusercontent.com/17810985/134784366-f352ff1e-058e-4739-a2f5-655da6d73aaa.png)

**Comment by emukidid** [comment]
It's because SD2SP2 has a higher priority in the device list and once we find it, that's the only device that will be looked at for boot.dol. Otherwise we'd have to seek down the list to mount and try to find a boot.dol on every device that supports boot.dol when in actual fact you don't have one and you just want to boot Swiss to play a game :) What I'm trying to say is that you have a niche use case and I'd rather not make the experience poorer for the majority use case.

If it's because it's difficult to remove the SD card from SD2SP2 to update boot.dol, you could just use Swiss itself to copy boot.dol from SD Gecko to SD2SP2?

Happy to be told otherwise if there's something I've missed.
