### ISSUE TITLE
[Question]: doubt on the wii swiss doesn't work . get a black screen

### ISSUE THREAD

**Issue by alimao10** [emukidid/swiss-gc#722]
### Describe your question

current versions i get black screen on wii, some old versions were compatible with wii, does anyone know how to solve this problem or on wii swiss was it discontinued?

**Comment by Rulumi** [comment]
It works fine here on two consoles.
What method are you using to launch it?
If you are trying to launch directly from Wii homebrew to MIOS, try with Wii Swiss Booter, other launchers can be hit or miss with launching Swiss or GameCube homebrew in general.
Also remember that that method _requires_ a cMIOS.

**Comment by alimao10** [comment]
> It works fine here on two consoles, what method are you using to launch it?
> 
> If you are trying to launch it directly from Wii homebrew to MIOS, try with Wii Swiss Booter, other launchers can be hit or miss with launching Swiss or GameCube homebrew in general.
> 
> Also remember that that method _requires_ a cMIOS.

I used homebrew launcher, I don't know this Wii Swiss Booster
i installed cmios

**Comment by Rulumi** [comment]
Some launchers can have problems launching some homebrew and new versions of Swiss properly, I know that the "Wii Swiss Booter" works fine for launching Swiss and it's easy to find it by searching it on Google, so that's a good option to give a try to.

Get the latest version of it, put the app folder inside an "apps" folder on the root of the SD Card, rename the Swiss Booter app folder to "Swiss". Finally extract the uncompressed version of the Swiss .dol inside the app folder and rename the Swiss dol to "swiss.dol".

Now launching the Booter app from the Homebrew Launcher should work if the proper cMIOS is installed and the Swiss dol is on the correct path. But remember to do from the SDGecko, so Swiss can detect the SDGecko at launch.

**Comment by DraconicNEO** [comment]
> Also remember that that method _requires_ a cMIOS.

This is false I don't know why people keep saying this but I was able to boot Swiss just fine without cMIOS using WiiXplorer. You just need to launch it as GC Homebrew and it will launch it in GameCube mode without any issues.

**Comment by Extrems** [comment]
You need a cMIOS for that WiiXplorer feature to work.

**Comment by DraconicNEO** [comment]
> You need a cMIOS for that WiiXplorer feature to work.

That's strange then because I have no cMIOS installed on this Wii, just MIOS v10 and it loads up just fine. Is cMIOS needed for SD card access or something?

**Comment by Extrems** [comment]
No, it's needed for it to work at all.

**Comment by DraconicNEO** [comment]
> No, it's needed for it to work at all.

Wait then how is it working without cMIOS?

**Comment by Extrems** [comment]
The only logical explanation is that you do have a cMIOS.

**Comment by DraconicNEO** [comment]
> The only logical explanation is that you do have a cMIOS.

Maybe, I don't remember installing it though I practically exclusively use only Nintendont for Gamecube games on Wii.
