### ISSUE TITLE
[Issue]: Optimise for RetroTINK-4K option and PAL video

### ISSUE THREAD

**Issue by cobhc2019** [emukidid/swiss-gc#880]
### Describe the bug

I use shinehax and so I have to have Swiss run in 576i or 576p mode to avoid setting the progressive mode flag to on preventing shinehax from working. This works fine if you only play NTSC games or don't use IGR to boot back into Swiss. If you play a PAL game and then use IGR to boot back to Swiss, the image becomes vertically stretched and stays like that until the video mode is changed away from the current one and back again. If I do a full reboot as opposed to using IGR, there is no issue.

### Steps to reproduce

1. Set Optimise for RetroTINK-4K option to on.
2. Set Swiss Video mode to 576i or 576p.
3. Launch a PAL game.
4. IGR back to Swiss.

### Expected behavior

Image is not stretched after IGR.

### Add screenshots

![20240614_001937](https://github.com/emukidid/swiss-gc/assets/53277004/c96a15cb-b02b-4d37-99ad-d763015e40a3)

**Comment by Nashismo** [comment]
What cables or adapters are you using to get your image on the screen? Because if you are using Retrotink component cables, Extrems won't help you. It has nothing to do with anything, but that is how he rationalize things. Also, don't stutter or talk about someone/something he may not like, because he will use it as an excuse not to help you.

**Comment by cobhc2019** [comment]
I'm using a Carby on GCVideo 3.1 into an RT4K lol

**Comment by Nashismo** [comment]
> I'm using a Carby on GCVideo 3.1 into an RT4K lol

Good, I think he likes those expensive adapters, but don't cheap out on anything else. Maybe you have a non expensive TV, if you do, be careful not to tell Extrems about it. All in all, you are fine, for now, lol

**Comment by Nashismo** [comment]
> I'm using a Carby on GCVideo 3.1 into an RT4K lol

Also it seems Extrems doesn't have a sense of humour, and my comments, censored... actions speak for themselves, so no need to add more.

**Comment by Nashismo** [comment]
My comments deleted. Why? Because I told the TRUTH, the guy refuses to help in anything because he is pissed with someone that made those cables? What that has to do with my petition? Now you want to have a good excuse to censor me you dipshit Extrems? You should mention you are fuc&king as/shole before opening any petition, so I know who I am talking with. Or, so I don't waste my fuc/king time trying to ask for anything like a dumbass.

**Comment by Extrems** [comment]
Fixed in 7b00deb (r1683).
